### ISSUE TITLE
Module usage 

### ISSUE THREAD

**Issue by vipin-kumar-ext** [vmware/ansible-role-kubernetes-master#2]
Hi
Why a module cant be used to create secret ?

 name: Create Docker Registry secret
  command: kubectl create secret docker-registry "{{ kube_docker_registry_secret_name }}" --docker-server="{{ kube_docker_registry_server }}" --docker-username="{{ kube_docker_registry_username }}" --docker-password="{{ kube_docker_registry_pwd }}" --docker-email="{{ kube_docker_registry_email }}"
  ignore_errors: true
  when: "{{ kube_docker_registry_secret_name }}"
  tags:

**Comment by tompscanlan** [comment]
Hi @vipin-kumar-ext thanks for feedback.

This module had a specific purpose and has since fallen out of use.  There are likely better modules to do what you need. I'm closing this because fixing it is out of scope at the moment.
